### Recuperar todas las peliculas
GET http://localhost:1234/movies


### Recuperar una pelicula por id
GET http://localhost:1234/movies/a5b3087a-90b5-11ef-a5ec-408d5c9a99f8


### Recuperartodas las peliculas por un genero
GET http://localhost:1234/movies?genre=drama


### Crear una pelicula con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The GodFather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ]
}



### Actualizar una pelicula
PATCH http://localhost:1234/movies/a8418682-9241-11ef-a5ec-408d5c9a99f8
Content-Type: application/json

{
    "year": 2010
}




### Borrar una prlicula
DELETE http://localhost:1234/movies/a29129bd-924b-11ef-a5ec-408d5c9a99f8





